### ISSUE TITLE
Organizers

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#1]
I'm looking for some additional organizers who have the time to help with maintaining the repo, finding mentors, venues, and hopefully sponsors.

I work right near city hall so if anyone wants to meet up during a lunch, after work, or at a meetup I will make myself available. Leave me a message here or send me a tweet @adobley.

Thanks! I'm excited to get this off the ground.

**Comment by rosskukulinski** [comment]
Hi @adobley.  Congrats on getting this going!  I'm one of the organizers for [BayNode](www.meetup.com/BayNode/) and have mentored at several nodeschools over the years.  I'm moving to Philadelphia in December and am looking forward to getting involved with the philly node scene in January.

**Comment by adobley** [comment]
Awesome! Be sure to remember us when you move. 

If you want to lend any experience in the meantime I'd be happy to have it.

**Comment by rosskukulinski** [comment]
@adobley sure thing!  The nodeschool website has a ton of info (which I'm you've probably read already to get you to this point).  Also the nodejs/evangelism group is working on recommendations/suggestions for running meetups - you can follow that discussion here: https://github.com/nodejs/evangelism/issues/162

Beyond that, I'm happy to share my experiences running BayNode over the last 2 years here in California.  You can email me at ross at getyodlr.com and we can setup a time.

Oh, and I'll be in the city apartment hunting November 11-14 and would love to meet local folks in person if there's an event then.
