### ISSUE TITLE
Add Mike to Philadelphia Org

### ISSUE THREAD

**Issue by mattmorgis** [nodeschool/philadelphia#10]
@nodeschoolbot add-user mflamb

**Comment by mattmorgis** [comment]
@nodeschoolbot add-user mflamb

**Comment by riyadhalnur** [comment]
I have added @mflamb to the `chapter-organizers` team.

**Comment by mattmorgis** [comment]
@nodeschoolbot add-team-user philadelphia mflamb

**Comment by riyadhalnur** [comment]
I cannot find the team `philadelphia`

**Comment by riyadhalnur** [comment]
I have invited @mflamb to the `philadelphia` team.
