### ISSUE TITLE
Mentors

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#2]
I'm looking to build up a roster of interested mentors.

I do not have a date for the first event yet, but if you are interested and want me to contact you when we have a date leave me your info. I work right in center city and go to a number of meetups so I can make myself available if you have any concerns and want to talk it over offline. 

Also check out the [NodeSchool website section on mentoring](http://nodeschool.io/mentor-at-event.html).

**Comment by amsross** [comment]
I wouldn't say I've got a ton of availability, but I also work in Center City and would love to show up and help out where I can. You can get me in `phillydev` as **mattross**.

**Comment by jsumnersmith** [comment]
@adobley How many mentors do we have coming on Saturday? I know a few people from P'unk Ave were looking to show up and could act as mentors.

**Comment by adobley** [comment]
@jsumnersmith, definitely interested in getting more mentors. There are "mentor tickets" on the ti.to page, but so far only one mentor has gone that route and signed up there. I have a few maybes, Linode is sending at least one person, and I'm talking to a few others currently.

**Comment by jsumnersmith** [comment]
@adobley Great. I have about 2-3 people here from P'unk Ave.

**Comment by adobley** [comment]
Excellent :)
