### ISSUE TITLE
NodeSchool Philly logo

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#3]
We need a NodeSchool Philly logo so we can make stickers and other swag that people might be interested in to promote the events.

I'll try to work on this when I have time but if someone else wants to take a run at it I'd love that.

**Comment by adobley** [comment]
Heres my first pass at a logo.

Looking for comments, this isn't my domain so I'm sure it could be better.
![phillynslogo](https://cloud.githubusercontent.com/assets/9088981/10547627/9b1d4e90-7403-11e5-9062-6c859cf2b132.png)

**Comment by johnmanko** [comment]
nice.
