### ISSUE TITLE
NodeSchool Philadelphia #1 Venue

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#4]
I'm on the hunt for a venue for the first meetup. It would likely be best to look at a minimum a month out for a space so we can get mentors, spread the word, and try to find some sponsors.

I'll post with updates and if anyone has any suggestions I'd appreciate any leads.

**Comment by jsumnersmith** [comment]
@adobley Let me check in with the team here at P'unk Ave. We have some space that could work.

**Comment by jsumnersmith** [comment]
@adobley We're interested here. We've got a few different spaces that could work. Up to maybe 15 or 20 people attending (plus mentors).

**Comment by adobley** [comment]
@jsumnersmith That would be amazing. I was thinking it would be best to aim for a
Saturday event. I need some time still to try to drum up some sponsors,
mentors, and spread the word. I was thinking the 31st at the earliest, but
I'm not sure what your locations availability is.

Would you want to go over details here or talk some things over in person?
I can head over for a lunch meeting some time. I'm right near city hall and
can grab the BSL down.

**Comment by jsumnersmith** [comment]
Hey @adobley could you swing by towards the end of the day either Wednesday or Thursday this week? :beers: on us.

**Comment by adobley** [comment]
@jsumnersmith definitely. Wednesday works for me. Any time work best?

**Comment by jsumnersmith** [comment]
Could you do 4:00?

**Comment by adobley** [comment]
Sure, see you then.

**Comment by jsumnersmith** [comment]
Awesome. Address is 1168 E. Passyunk!
