### ISSUE TITLE
Year of NodeSchool

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#6]
Currently one of the ideas under consideration is a series of shorter(2-4 hour) meetups where we focus on one specific NodeSchool workshop in each session.

The idea is to have a Year of NodeSchool that can help take individuals through all the workshops with explanations, volunteers explaining their process to solving problems, and a bit more context to the material.

My biggest concern with this is that a year is a mighty long time and I think a fair number of people will move on with the workshoppers independently rather than wait for a week or a month for the next session.

I'd love to hear more of what others think of the idea and how we can keep people engaged.

**Comment by rosskukulinski** [comment]
@adobley I like the idea, but i agree a year is probably too long of a time.  It's also important IMO to always have few mentors on hand to welcome completely new users and get them started with the first module, even if everyone else is working on a more advanced one.
