### ISSUE TITLE
Resurrecting Philadelphia Chapter

### ISSUE THREAD

**Issue by mattmorgis** [nodeschool/philadelphia#8]
Hi,

@tamera-lanham and I are interested in resurrecting the Philadelphia Chapter in 2018. 

We can host the events at Elsevier Inc., located in Center City across from Love Park. A few of our co-workers at Elsevier are interested in mentoring the events as well. 

cc/
@rosskukulinski @adobley @bnb

**Comment by adobley** [comment]
That would be wonderful. I've unfortunately been 100% travel for the past year and some change so I haven't been able to host. I've looked for someone to take over a few times but haven't had any success. I'll start getting it setup. I have a new logo I never was able to debut as well. Might be nice for a fresh launch :)

**Comment by adobley** [comment]
Invited both to the org #9 

I think I've done everything but let me know if I can do anything to help. I'm in town recently but don't know for how long. Always more than happy to be a mentor or help with organizing when I'm in town.

**Comment by rosskukulinski** [comment]
@MattMorgis would love to see this group going again.  Like @adobley, my work & personal life have kept my extracurricular activities to a minimum.  👍

**Comment by realgoatish** [comment]
@adobley I'm helping @MattMorgis out with getting the Philly chapter up and running again.  I'll be heading to Baltimore's next event on May 6th to get a stronger sense of how this thing should look on the ground, but I would welcome any feedback from you too.  Maybe we could schedule a time to talk on the phone for a few minutes, just so I can get a sense of what your experience was like with running events.  If this sounds possible for you, please send me an email so we can set up a time.  Thanks! mflambjr@gmail.com
