### ISSUE TITLE
Add Matt and Tamera to Philadelphia Org

### ISSUE THREAD

**Issue by adobley** [nodeschool/philadelphia#9]
@nodeschoolbot add-team-user philadelphia MattMorgis

**Comment by adobley** [comment]
@nodeschoolbot add-team-user philadelphia tamera-lanham

**Comment by riyadhalnur** [comment]
I cannot find the team `philadelphia`

**Comment by riyadhalnur** [comment]
I have invited @tamera-lanham to the `philadelphia` team.

**Comment by adobley** [comment]
@nodeschoolbot add-team-user philadelphia MattMorgis

**Comment by riyadhalnur** [comment]
I cannot find the team `philadelphia`

**Comment by riyadhalnur** [comment]
I have invited @MattMorgis to the `philadelphia` team.

**Comment by mattmorgis** [comment]
Hm, may I ask what the expected outcome of the bot command is suppose to be? I at least didn't get any type of invitation e-mail, nor do I have any extra permissions on this repo.

**Comment by adobley** [comment]
Should have added to the philadelphia team. https://github.com/orgs/nodeschool/teams/philadelphia/members

Lets try something else. Might need to be in the chapter organizers group first. First time using the bot.

**Comment by adobley** [comment]
@nodeschoolbot add-user MattMorgis

**Comment by riyadhalnur** [comment]
I have added @MattMorgis to the `chapter-organizers` team.

**Comment by adobley** [comment]
@nodeschoolbot add-user tamera-lanham

**Comment by riyadhalnur** [comment]
I have added @tamera-lanham to the `chapter-organizers` team.

**Comment by mattmorgis** [comment]
Nice! That worked! I'm now in the [`chapter-organizers`](https://github.com/orgs/nodeschool/teams/chapter-organizers/members) team.

**Comment by adobley** [comment]
@MattMorgis That should give you admin over the repo. The Philadelphia team only has write anyway(that is how it was setup by default).

**Comment by mattmorgis** [comment]
@nodeschoolbot add-team-user philadelphia MattMorgis

**Comment by riyadhalnur** [comment]
I cannot find the team `philadelphia`

**Comment by riyadhalnur** [comment]
I have invited @MattMorgis to the `philadelphia` team.
